### ISSUE TITLE
Come up with categories

### ISSUE THREAD

**Issue by icco** [icco/postmortems#1]
Hi @DamianFekete, @max-sixty and @gnomon-,

Today I built this repository using the data in https://github.com/danluu/post-mortems. In the data folder, you'll see lots of files. Each one is a pm from Dan's repo.

I'd like for there to be a hard coded list of categories, and I'd love your input. So far I have:

 - time
 - config-change
 - security
 - undescriptive
 - cloud
 - cascading-failure
 - automation

Thoughts on other categories that would be good to start with?

**Comment by icco** [comment]
Closing this, as we have a set for now: https://github.com/icco/postmortems/blob/master/postmortem.go#L35-L45

**Comment by BigEd** [comment]
Sorry, I'm a bit late to this party! The new forum set up in the hope of continuing the community on G+ has tags, which might be of interest:
https://postmortems.info/tags
